In [1]:
#modules for data preprocessing
import pandas as pd
import numpy as np
import re
import string


import nltk
#from nltk.corpus import stopwords
#from nltk.tokenize import word_tokenize 
#from nltk.stem.porter import *
#from nltk.stem.wordnet import WordNetLemmatizer

#modules for feature representation
from sklearn.feature_extraction.text import TfidfVectorizer

#modules for training 
from sklearn.model_selection import train_test_split, KFold, cross_val_score, cross_val_predict

from sklearn.linear_model import LogisticRegression
#from sklearn.naive_bayes import MultinomialNB
#from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

from numpy import mean
from numpy import std
import sklearn.metrics as metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score



# Task1

In [2]:
#load the training data

pd.set_option('display.max_colwidth', 100)

df1 = pd.read_csv('/Users/dufflelee/COS80027/assignment1/datasets/x_train.csv', header=None, dtype=str)
df2 = pd.read_csv('/Users/dufflelee/COS80027/assignment1/datasets/y_train.csv', header=None, dtype=str)

df1.columns = ['category', 'msg']
df2.columns = ['sentiment']


print(df1, df2)
df1.head()

     category  \
0      amazon   
1      amazon   
2      amazon   
3      amazon   
4      amazon   
...       ...   
2395     yelp   
2396     yelp   
2397     yelp   
2398     yelp   
2399     yelp   

                                                                                                      msg  
0                            Oh and I forgot to also mention the weird color effect it has on your phone.  
1                                                                            THAT one didn't work either.  
2                                                                                      Waste of 13 bucks.  
3     Product is useless, since it does not have enough charging current to charge the 2 cellphones I ...  
4                               None of the three sizes they sent with the headset would stay in my ears.  
...                                                                                                   ...  
2395                                   

category  \
0   amazon   
1   amazon   
2   amazon   
3   amazon   
4   amazon   

                                                                                                   msg  
0                         Oh and I forgot to also mention the weird color effect it has on your phone.  
1                                                                         THAT one didn't work either.  
2                                                                                   Waste of 13 bucks.  
3  Product is useless, since it does not have enough charging current to charge the 2 cellphones I ...  
4                            None of the three sizes they sent with the headset would stay in my ears.

In [3]:
#remove punctuation in x_train.csv

def remove_punctuation(msg):
    msg_nopunt = "".join([c for c in msg if c not in string.punctuation])
    return msg_nopunt

df1['msg'] = df1['msg'].apply(lambda x: remove_punctuation(x))

print (df1)

df1.head()

     category  \
0      amazon   
1      amazon   
2      amazon   
3      amazon   
4      amazon   
...       ...   
2395     yelp   
2396     yelp   
2397     yelp   
2398     yelp   
2399     yelp   

                                                                                                      msg  
0                             Oh and I forgot to also mention the weird color effect it has on your phone  
1                                                                              THAT one didnt work either  
2                                                                                       Waste of 13 bucks  
3     Product is useless since it does not have enough charging current to charge the 2 cellphones I w...  
4                                None of the three sizes they sent with the headset would stay in my ears  
...                                                                                                   ...  
2395                                   

category  \
0   amazon   
1   amazon   
2   amazon   
3   amazon   
4   amazon   

                                                                                                   msg  
0                          Oh and I forgot to also mention the weird color effect it has on your phone  
1                                                                           THAT one didnt work either  
2                                                                                    Waste of 13 bucks  
3  Product is useless since it does not have enough charging current to charge the 2 cellphones I w...  
4                             None of the three sizes they sent with the headset would stay in my ears

In [4]:
#convert to lower case in x_train.csv
df1 = df1.apply(lambda x: x.astype(str).str.lower())

print (df1)

df1.head()


     category  \
0      amazon   
1      amazon   
2      amazon   
3      amazon   
4      amazon   
...       ...   
2395     yelp   
2396     yelp   
2397     yelp   
2398     yelp   
2399     yelp   

                                                                                                      msg  
0                             oh and i forgot to also mention the weird color effect it has on your phone  
1                                                                              that one didnt work either  
2                                                                                       waste of 13 bucks  
3     product is useless since it does not have enough charging current to charge the 2 cellphones i w...  
4                                none of the three sizes they sent with the headset would stay in my ears  
...                                                                                                   ...  
2395                                   

category  \
0   amazon   
1   amazon   
2   amazon   
3   amazon   
4   amazon   

                                                                                                   msg  
0                          oh and i forgot to also mention the weird color effect it has on your phone  
1                                                                           that one didnt work either  
2                                                                                    waste of 13 bucks  
3  product is useless since it does not have enough charging current to charge the 2 cellphones i w...  
4                             none of the three sizes they sent with the headset would stay in my ears

# Task2

In [5]:
#Feature representation on x_train.csv review col

vec = TfidfVectorizer(stop_words='english',min_df=5, max_df=0.75, ngram_range=(1, 2), binary=False, use_idf=True, smooth_idf=True)
bag_of_words = vec.fit_transform(df1.msg)

tfidf_array = bag_of_words.toarray()

pd.DataFrame(data=tfidf_array,columns=vec.get_feature_names())
#bag_of_words_train = pd.DataFrame(data=tfidf_array,columns=vec.get_feature_names())





10   12   20   40  absolutely  acting  action  actor  actors  actually  \
0     0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
1     0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
2     0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
3     0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
4     0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
...   ...  ...  ...  ...         ...     ...     ...    ...     ...       ...   
2395  0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
2396  0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
2397  0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
2398  0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   
2399  0.0  0.0  0.0  0.0         0.0     0.0     0.0    0.0     0.0       0.0   

      ...  worst  worth  wouldnt  writing  written  wrong  year  years  youd  \
0     ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
1     ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
2     ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
3     ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
4     ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
...   ...    ...    ...      ...      ...      ...    ...   ...    ...   ...   
2395  ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
2396  ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
2397  ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
2398  ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   
2399  ...    0.0    0.0      0.0      0.0      0.0    0.0   0.0    0.0   0.0   

      zero  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
2395   0.0  
2396   0.0  
2397   0.0  
2398   0.0  
2399   0.0  

[2400 rows x 552 columns]

In [6]:
#For report infor only

print(bag_of_words)

print("Vocabulary size: {}".format(len(vec.vocabulary_)))
print("Vocabulary content:\n {}".format(vec.vocabulary_))

vec.get_feature_names()

  (0, 344)	0.31956144103444933
  (0, 96)	0.5502807915770779
  (0, 309)	0.5502807915770779
  (0, 329)	0.5406131576706172
  (1, 535)	0.6982821801457092
  (1, 126)	0.7158226015508
  (2, 518)	1.0
  (3, 498)	0.3496527507563435
  (3, 80)	0.42678791744834005
  (3, 82)	0.4798518322692818
  (3, 137)	0.374131302703228
  (3, 500)	0.46010825152617263
  (3, 376)	0.3371400475938127
  (4, 148)	0.6369559257043312
  (4, 451)	0.6037305418072229
  (4, 228)	0.47937102707537055
  (5, 110)	0.5560882857282538
  (5, 426)	0.38713439808502775
  (5, 109)	0.5560882857282538
  (5, 542)	0.48130925066007946
  (6, 274)	1.0
  (7, 433)	0.6546280401065828
  (7, 442)	0.4901841735628304
  (7, 303)	0.5754838008968969
  (8, 476)	0.6569039142921478
  :	:
  (2392, 281)	0.5075825303885267
  (2392, 262)	0.4467955620700384
  (2393, 446)	0.8703001974423817
  (2393, 214)	0.4925216404704989
  (2394, 351)	0.3711089968062013
  (2394, 410)	0.4862273486153562
  (2394, 369)	0.47398702879123844
  (2394, 140)	0.4097602053597404
  (2394, 1

['10',
 '12',
 '20',
 '40',
 'absolutely',
 'acting',
 'action',
 'actor',
 'actors',
 'actually',
 'ago',
 'amazing',
 'amazon',
 'amp',
 'annoying',
 'anytime',
 'anytime soon',
 'area',
 'arrived',
 'art',
 'ask',
 'atmosphere',
 'attentive',
 'audio',
 'authentic',
 'average',
 'avoid',
 'away',
 'awesome',
 'awful',
 'bad',
 'bar',
 'barely',
 'bars',
 'basically',
 'battery',
 'battery life',
 'beautiful',
 'beef',
 'beer',
 'believable',
 'believe',
 'belt',
 'best',
 'better',
 'big',
 'bit',
 'black',
 'bland',
 'blue',
 'bluetooth',
 'bluetooth headset',
 'boring',
 'bother',
 'bought',
 'breakfast',
 'brilliant',
 'bring',
 'broke',
 'buffet',
 'burger',
 'business',
 'buttons',
 'buy',
 'buying',
 'cable',
 'calls',
 'came',
 'camera',
 'car',
 'care',
 'case',
 'cases',
 'cast',
 'casting',
 'cell',
 'cell phone',
 'certainly',
 'character',
 'characters',
 'charge',
 'charger',
 'charging',
 'charm',
 'cheap',
 'check',
 'chicken',
 'child',
 'chips',
 'cinema',
 'cinemat

# Task3

In [7]:
#data spliting 

x_train, x_test, y_train, y_test = train_test_split(tfidf_array, df2['sentiment'], test_size=0.2, random_state=1)

print (x_train.shape, y_train.shape,x_test.shape, y_test.shape)
print (x_train, x_test, y_train, y_test)

(1920, 552) (1920,) (480, 552) (480,)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 2199    1
1070    0
1264    1
1938    0
1737    0
       ..
960     0
905     0
1096    0
235     0
1061    0
Name: sentiment, Length: 1920, dtype: object 1348    1
468     1
1463    1
2267    1
943     0
       ..
1386    1
1384    1
902     0
2036    1
1418    1
Name: sentiment, Length: 480, dtype: object


In [8]:

df2['sentiment']

0       0
1       0
2       0
3       0
4       0
       ..
2395    1
2396    1
2397    1
2398    1
2399    1
Name: sentiment, Length: 2400, dtype: object

In [9]:
#define training algorithm

logreg = LogisticRegression()


#cross validation

cv = KFold(n_splits=10)

scores = cross_val_score(logreg, x_train, y_train, scoring='accuracy', cv=cv, n_jobs=1)
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

predictions = cross_val_predict(logreg, x_test, y_test, cv=cv)
#print(predictions)
predictions_int = predictions.astype(int)
print(predictions_int)
print(predictions.shape)


Accuracy: 0.780 (0.025)
[0 1 1 1 1 0 0 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 0
 0 0 1 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 1
 1 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1 1
 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1
 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 0
 1 0 1 0 1 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 1 1 0 1 0 0 0
 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1
 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 1
 1 0 1 0 1 1 1 0 0 1 1 1 0 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 1 1 0 1 0 1 1
 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0
 0 0 1 1 1 1 1 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 0 1 0]
(4

In [10]:
#Hyperparameters search for model

# define models and parameters
model = LogisticRegression()
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]

# define grid search
grid = dict(solver=solvers,penalty=penalty,C=c_values)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)

grid_result = grid_search.fit(x_train, y_train)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))


Best: 0.780208 using {'C': 1.0, 'penalty': 'l2', 'solver': 'newton-cg'}
0.741667 (0.027283) with: {'C': 100, 'penalty': 'l2', 'solver': 'newton-cg'}
0.742188 (0.026988) with: {'C': 100, 'penalty': 'l2', 'solver': 'lbfgs'}
0.741667 (0.027283) with: {'C': 100, 'penalty': 'l2', 'solver': 'liblinear'}
0.770833 (0.032858) with: {'C': 10, 'penalty': 'l2', 'solver': 'newton-cg'}
0.770833 (0.032858) with: {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}
0.770833 (0.032858) with: {'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}
0.780208 (0.025065) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'newton-cg'}
0.779687 (0.024875) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'lbfgs'}
0.780208 (0.025065) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'liblinear'}
0.763542 (0.024004) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}
0.763542 (0.024004) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
0.763542 (0.023776) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
0.664583 (0.034564) wit

In [11]:
#Train model on the training set using LogsticRegression 

logreg = LogisticRegression(C=1, penalty='l2', n_jobs=1, solver='newton-cg', class_weight='balanced')

logreg.fit(x_train, y_train)

print('Training set score: {:.3f}'.format(logreg.score(x_train, y_train)))
print('Validation set score: {:.3f}'.format(logreg.score(x_test, y_test)))

Training set score: 0.865
Validation set score: 0.800


In [12]:
#Evaluating performances of the model on validation set

pred_logreg = logreg.predict(x_test)
confusion = confusion_matrix(y_test, pred_logreg)
print('Confusion matrix:\n{}'.format(confusion))


print('\n Accuracy of the classifier is',metrics.accuracy_score(y_test, pred_logreg))
print('\n Precision is',metrics.precision_score(y_test, pred_logreg, pos_label='1'))
print('\n Recall score is',metrics.recall_score(y_test, pred_logreg, pos_label='1'))
print('\n F1 score is',metrics.f1_score(y_test, pred_logreg, pos_label='1'))

Confusion matrix:
[[192  37]
 [ 59 192]]

 Accuracy of the classifier is 0.8

 Precision is 0.8384279475982532

 Recall score is 0.7649402390438247

 F1 score is 0.8


In [13]:
#Test model using x_test.csv

import pickle

filename = 'tfidf_model.sav'
pickle.dump(logreg, open(filename, 'wb'))

loaded_model = pickle.load(open(filename, 'rb'))

#take col 1 of x_test.csv
df3 = pd.read_csv("/Users/dufflelee/COS80027/assignment1/datasets/x_test.csv", usecols=[1])
df4 = pd.read_csv("/Users/dufflelee/COS80027/assignment1/datasets/y_test.csv", usecols=[0])

#Combining the x_test.csv y_test.csv
df=pd.concat([df3, df4],axis=1) 
df.columns = ['review', 'sentiment']
df


review  \
0                                                      Disappointing accessory from a good manufacturer.   
1    The one big drawback of the MP3 player is that the buttons on the phone's front cover that let y...   
2                                    This particular model would not work with my Motorola Q smartphone.   
3    If the two were seperated by a mere 5+ ft I started to notice excessive static and garbled sound...   
4                           Also the area where my unit broke).- I'm not too fond of the magnetic strap.   
..                                                                                                   ...   
594                                                                  Everything was fresh and delicious!   
595                                                                                               #NAME?   
596                                                                                Pretty awesome place.   
597                                                          The staff are great, the ambiance is great.   
598                                                              The patio seating was very comfortable.   

     sentiment  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
594          1  
595          1  
596          1  
597          1  
598          1  

[599 rows x 2 columns]

In [14]:
X_TEST=df['review']
Y_TEST=df['sentiment']

In [15]:

#feature representation on x test data 
X_TEST_tfidf =  vec.transform(X_TEST).toarray()

#predict on x test data 
result = loaded_model.predict(X_TEST_tfidf)

#change result string array to int array
Y_RESULT = result.astype(int)
Y_RESULT

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,

In [16]:
X_TEST_tfidf 

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
Y_TEST

0      0
1      0
2      0
3      0
4      0
      ..
594    1
595    1
596    1
597    1
598    1
Name: sentiment, Length: 599, dtype: int64

In [18]:
#Evaluating performances of the model on test set

confusion = confusion_matrix(Y_TEST,Y_RESULT)
print('Confusion matrix:\n{}'.format(confusion))


print('\n Accuracy of the classifier is',metrics.accuracy_score(Y_TEST,Y_RESULT))
print('\n Precision is',metrics.precision_score(Y_TEST,Y_RESULT))
print('\n Recall score is',metrics.recall_score(Y_TEST,Y_RESULT))
print('\n F1 score is',metrics.f1_score(Y_TEST, Y_RESULT))

Confusion matrix:
[[240  59]
 [ 94 206]]

 Accuracy of the classifier is 0.7445742904841403

 Precision is 0.7773584905660378

 Recall score is 0.6866666666666666

 F1 score is 0.7292035398230088
